production deployment fix

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -20,52 +20,52 @@ jobs:
       - uses: actions/checkout@v4
       - uses: superfly/flyctl-actions/setup-flyctl@master
 
-    #   - name: Install
-    #     run: |
-    #       npm install
-    #       npm run install-backend
-    #       npm run install-frontend
-
-    #   - name: Prisma code generator
-    #     run: (cd backend && npx prisma generate)
-
-    #   - name: Test build
-    #     run: npm run build  # redundant, but need check that it builds
-
-    #   # TODO@P3: Can it be simplified?
-    #   - name: Check DB format integrity
-    #     run: (export DATABASE_URL="file:///tmp/test.db" && npm run db:setup && cd backend && npx prisma migrate status)
-
-      # Above checks have been already done in staging deployment.
-      - name: Verify staging deployment exists
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Install
         run: |
-          SHA="${GITHUB_SHA}"
-          REPO="${GITHUB_REPOSITORY}"
+          npm install
+          npm run install-backend
+          npm run install-frontend
 
-          DEPLOYMENTS=$(curl -s \
-            -H "Authorization: Bearer $GH_TOKEN" \
-            -H "Accept: application/vnd.github+json" \
-            "https://api.github.com/repos/$GITHUB_REPOSITORY_OWNER/$REPO/deployments?environment=staging&sha=$SHA")
+      - name: Prisma code generator
+        run: (cd backend && npx prisma generate)
 
-          DEPLOYMENT_ID=$(echo "$DEPLOYMENTS" | jq '.[0].id')
+      - name: Test build
+        run: npm run build  # redundant, but need check that it builds
 
-          if [ "$DEPLOYMENT_ID" = "null" ]; then
-            echo "ERROR: Commit was never deployed to staging."
-            exit 1
-          fi
+      # TODO@P3: Can it be simplified?
+      - name: Check DB format integrity
+        run: (export DATABASE_URL="file:///tmp/test.db" && npm run db:setup && cd backend && npx prisma migrate status)
 
-          STATUS=$(curl -s \
-            -H "Authorization: Bearer $GH_TOKEN" \
-            -H "Accept: application/vnd.github+json" \
-            "https://api.github.com/repos/$REPO/deployments/$DEPLOYMENT_ID/statuses" \
-            | jq -r '.[0].state')
+    # This does not work due to `git merge` creating new commits :-(
+    #   - name: Verify staging deployment exists
+    #     env:
+    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #     run: |
+    #       SHA="${GITHUB_SHA}"
+    #       REPO="${GITHUB_REPOSITORY}"
 
-          if [ "$STATUS" != "success" ]; then
-            echo "ERROR: Staging deployment did not succeed."
-            exit 1
-          fi
+    #       DEPLOYMENTS=$(curl -s \
+    #         -H "Authorization: Bearer $GH_TOKEN" \
+    #         -H "Accept: application/vnd.github+json" \
+    #         "https://api.github.com/repos/$GITHUB_REPOSITORY_OWNER/$REPO/deployments?environment=staging&sha=$SHA")
+
+    #       DEPLOYMENT_ID=$(echo "$DEPLOYMENTS" | jq '.[0].id')
+
+    #       if [ "$DEPLOYMENT_ID" = "null" ]; then
+    #         echo "ERROR: Commit was never deployed to staging."
+    #         exit 1
+    #       fi
+
+    #       STATUS=$(curl -s \
+    #         -H "Authorization: Bearer $GH_TOKEN" \
+    #         -H "Accept: application/vnd.github+json" \
+    #         "https://api.github.com/repos/$REPO/deployments/$DEPLOYMENT_ID/statuses" \
+    #         | jq -r '.[0].state')
+
+    #       if [ "$STATUS" != "success" ]; then
+    #         echo "ERROR: Staging deployment did not succeed."
+    #         exit 1
+    #       fi
 
       - name: Deploy to production
         env:
